"""Library of memory addresses

Addresses are in WiiU virtual memory, and are correct for the 1.01E version
of the game
"""
from typing import NamedTuple


class Address(NamedTuple):
    address: int
    size: int
    struct: str


class Offset(NamedTuple):
    offset: int
    size: int
    struct: str


PLAYER = 0x1C38E5C8
characters = {
    "Player": Address(0x1C38E5C8, 0x057c, "1404s"),
    "Nagi": Address(0x1C38EB44, 0x057c, "1404s"),
    "L": Address(0x1C38F0C0, 0x057c, "1404s"),
    "Lao": Address(0x1C38F63C, 0x057c, "1404s"),
    "H.B.": Address(0x1C38FBB8, 0x057c, "1404s"),
    "Gwin": Address(0x1C390134, 0x057c, "1404s"),
    "Frye": Address(0x1C3906B0, 0x057c, "1404s"),
    "Doug": Address(0x1C390C2C, 0x057c, "1404s"),
    "Yelv": Address(0x1C3911A8, 0x057c, "1404s"),
    "Boze": Address(0x1C391724, 0x057c, "1404s"),
    "Phog": Address(0x1C391CA0, 0x057c, "1404s"),
    "Elma": Address(0x1C39221C, 0x057c, "1404s"),
    "Lin": Address(0x1C392798, 0x057c, "1404s"),
    "Celica": Address(0x1C392D14, 0x057c, "1404s"),
    "Irina": Address(0x1C393290, 0x057c, "1404s"),
    "Murderess": Address(0x1C39380C, 0x057c, "1404s"),
    "Alexa": Address(0x1C393D88, 0x057c, "1404s"),
    "Hope": Address(0x1C394304, 0x057c, "1404s"),
    "Mia": Address(0x1C394880, 0x057c, "1404s"),
}

# Character properties, relative to the character address
character_property_offsets = {
    "Name": Offset(0x0000, 64, "64s"),
    "name_length": Offset(0x40, 4, ">I"),
    # Appearance options
    "face": Offset(0x0044, 2, ">H"),
    "hair_style": Offset(0x0046, 2, ">H"),
    "hair_addon": Offset(0x0048, 2, ">H"),
    "moles": Offset(0x004a, 1, "B"),
    "freckles": Offset(0x004b, 1, "B"),
    "cheeks": Offset(0x004c, 1, "B"),
    "scars": Offset(0x004d, 1, "B"),
    "face_paint": Offset(0x004e, 2, ">H"),
    "eye_style": Offset(0x0050, 2, ">H"),
    "gender": Offset(0x0052, 4, ">I"),
    "voice": Offset(0x0056, 2, ">H"),
    "skin_tone": Offset(0x0058, 2, ">H"),
    "lips": Offset(0x005a, 2, ">H"),
    "eyeshadow": Offset(0x005c, 2, ">H"),
    "eye_color 1": Offset(0x005e, 2, ">H"),
    "eye_color 2": Offset(0x0060, 2, ">H"),
    "hair_color 1": Offset(0x0062, 2, ">H"),
    "hair_color 2": Offset(0x0064, 2, ">H"),
    "_padding_0x0066": Offset(0x0066, 2, "2x"),
    "height": Offset(0x0068, 4, ">f"),
    "chest_depth": Offset(0x006c, 4, ">f"),
    "chest_height": Offset(0x0070, 4, ">f"),
    "chest_width": Offset(0x0074, 4, ">f"),
    "_unknown_0x0078": Offset(0x0078, 2, ">H"),
    # end of appearance settings
    "level": Offset(0x007a, 1, "B"),
    "_padding_0x007b": Offset(0x007b, 1, "x"),
    "experience": Offset(0x007c, 4, ">I"),
    # Equipped gear
    "equipped_weapon_ranged": Offset(0x0080, 14, "14s"),
    "equipped_weapon_melee": Offset(0x008e, 14, "14s"),
    "equipped_primary_torso": Offset(0x009c, 14, "14s"),
    "equipped_primary_head": Offset(0x00aa, 14, "14s"),
    "equipped_primary_arm_r": Offset(0x00b8, 14, "14s"),
    "equipped_primary_arm_l": Offset(0x00c6, 14, "14s"),
    "equipped_primary_legs": Offset(0x00d4, 14, "14s"),
    "equipped_fashion_torso": Offset(0x00e2, 14, "14s"),
    "equipped_fashion_head": Offset(0x00f0, 14, "14s"),
    "equipped_fashion_arm_r": Offset(0x00fe, 14, "14s"),
    "equipped_fashion_arm_l": Offset(0x010c, 14, "14s"),
    "equipped_fashion_legs": Offset(0x011a, 14, "14s"),
    # end of equipped gear
    "class": Offset(0x0128, 1, "B"),
    "_padding_0x0129": Offset(0x0129, 1, "x"),
    "class_level": Offset(0x012a, 1, "B"),
    "_padding_0x12b": Offset(0x12b, 1, "x"),
    "class_exp": Offset(0x012c, 2, ">H"),
    # Arts values correspond to slots 4, 3, 2, 1, 8, 7, 6, 5
    "assigned_arts": Offset(0x012e, 16, ">8H"),
    "assigned_skills": Offset(0x013e, 10, ">5H"),
    "custom_soul_voice_prompts": Offset(0x0148, 8, ">4H"),
    "soul_voices": Offset(0x150, 32, ">16H"),
    "_unknown_0x0170": Offset(0x170, 516, "516s"),
    "bp": Offset(0x0374, 4, ">I"),
    "_padding_0x0378": Offset(0x0378, 1, "x"),
    # Ranks for arts & skills, values are 0 (locked) to 5 (MAX)
    "arts_levels": Offset(0x0379, 121, "121B"),
    "affinity_arts_levels": Offset(0x03f2, 36, "36b"),
    "_padding_0x0416": Offset(0x0416, 99, "99x"),  # padding to 256 bytes for all arts
    "skills_levels": Offset(0x0479, 94, "94b"),
    "_padding_0x0d7": Offset(0x04d7, 161, "161x"),  # padding to 256 bytes for all skills
    "affinity_points": Offset(0x0578, 2, ">H"),
    "affinity": Offset(0x057a, 1, "B"),
    "final_byte": Offset(0x057b, 1, "B"),
}

art_levels_offsets = {
    'ARTS_ASSAULT_AUTO_Na1': Offset(offset=889, size=1, struct="B"),
    'Decoy Round': Offset(offset=890, size=1, struct='B'),
    'Furious Blast': Offset(offset=891, size=1, struct='B'),
    'Burst Grenade': Offset(offset=892, size=1, struct='B'),
    'Flash Grenade': Offset(offset=893, size=1, struct='B'),
    'Assault Breaker': Offset(offset=894, size=1, struct='B'),
    'Medic Free': Offset(offset=895, size=1, struct='B'),
    'Takedown Shot': Offset(offset=896, size=1, struct='B'),
    'Power Dive': Offset(offset=897, size=1, struct='B'),
    'Last Stand': Offset(offset=898, size=1, struct='B'),
    'Gunforce': Offset(offset=899, size=1, struct='B'),
    'Flame Grenade': Offset(offset=900, size=1, struct='B'),
    'Assault Hammer': Offset(offset=901, size=1, struct='B'),
    'Infuriate': Offset(offset=902, size=1, struct='B'),
    'ARTS_ASSAULT_ARTS_14': Offset(offset=903, size=1, struct="B"),
    'ARTS_SNIPER_AUTO_Nam': Offset(offset=904, size=1, struct="B"),
    'First Down': Offset(offset=905, size=1, struct='B'),
    'Shrapnel': Offset(offset=906, size=1, struct='B'),
    'Eagle Eye': Offset(offset=907, size=1, struct='B'),
    'Sidewinder': Offset(offset=908, size=1, struct='B'),
    'Intercept': Offset(offset=909, size=1, struct='B'),
    'Hawkeye': Offset(offset=910, size=1, struct='B'),
    'Ghost Sniper': Offset(offset=911, size=1, struct='B'),
    'ARTS_DOUBLEHAND_AUTO': Offset(offset=912, size=1, struct="B"),
    'Sliding Slinger': Offset(offset=913, size=1, struct='B'),
    'Early Bird': Offset(offset=914, size=1, struct='B'),
    'Violent Streak': Offset(offset=915, size=1, struct='B'),
    'Primer': Offset(offset=916, size=1, struct='B'),
    'Executioner': Offset(offset=917, size=1, struct='B'),
    'Combat Limbo': Offset(offset=918, size=1, struct='B'),
    'Ghostwalker': Offset(offset=919, size=1, struct='B'),
    'ARTS_GATLING_AUTO_Na': Offset(offset=912, size=1, struct="B"),
    'Bullet Storm': Offset(offset=921, size=1, struct='B'),
    'Hellfire': Offset(offset=922, size=1, struct='B'),
    'Thermal Payload': Offset(offset=923, size=1, struct='B'),
    'Missile Volley': Offset(offset=924, size=1, struct='B'),
    'Enhanced Stand': Offset(offset=925, size=1, struct='B'),
    'Cool Off': Offset(offset=926, size=1, struct='B'),
    'ARTS_BEAMCANNON_AUTO': Offset(offset=927, size=1, struct="B"),
    'Beam Barrage': Offset(offset=928, size=1, struct='B'),
    'Subterfuge': Offset(offset=929, size=1, struct='B'),
    'Myopic Screen': Offset(offset=930, size=1, struct='B'),
    'Ether Blast': Offset(offset=931, size=1, struct='B'),
    'Gravity Blast': Offset(offset=932, size=1, struct='B'),
    'Gravity Cloak': Offset(offset=933, size=1, struct='B'),
    'Pathogen Blast': Offset(offset=934, size=1, struct='B'),
    'ARTS_PSYCHO_AUTO_Nam': Offset(offset=935, size=1, struct="B"),
    'Jetstream': Offset(offset=936, size=1, struct='B'),
    'Stellar Ray': Offset(offset=937, size=1, struct='B'),
    'Lightning Cloak': Offset(offset=938, size=1, struct='B'),
    'Starlight Kick': Offset(offset=939, size=1, struct='B'),
    'Astral Protection': Offset(offset=940, size=1, struct='B'),
    'Shooting Star': Offset(offset=941, size=1, struct='B'),
    'ARTS_SWORD_AUTO_Name': Offset(offset=942, size=1, struct="B"),
    'Rising Blade': Offset(offset=943, size=1, struct='B'),
    'Defensive Stance': Offset(offset=944, size=1, struct='B'),
    'Offensive Stance': Offset(offset=945, size=1, struct='B'),
    'Magnum Edge': Offset(offset=946, size=1, struct='B'),
    'Tornado Blade': Offset(offset=947, size=1, struct='B'),
    'Burning Slash': Offset(offset=948, size=1, struct='B'),
    'Incendiary Edge': Offset(offset=949, size=1, struct='B'),
    'Samurai Soul': Offset(offset=950, size=1, struct='B'),
    'ARTS_JAVELIN_AUTO_Na': Offset(offset=951, size=1, struct="B"),
    'Arcing Horn': Offset(offset=952, size=1, struct='B'),
    'Hair Trigger': Offset(offset=953, size=1, struct='B'),
    'Spiral Horn': Offset(offset=954, size=1, struct='B'),
    'Overwhelm': Offset(offset=955, size=1, struct='B'),
    'Speed Demon': Offset(offset=956, size=1, struct='B'),
    'Raijin': Offset(offset=957, size=1, struct='B'),
    'Trident Buster': Offset(offset=958, size=1, struct='B'),
    'ARTS_DOUBLEBLADE_AUT': Offset(offset=959, size=1, struct="B"),
    'Back Slash': Offset(offset=960, size=1, struct='B'),
    'Killing Machine': Offset(offset=961, size=1, struct='B'),
    'Side Slash': Offset(offset=962, size=1, struct='B'),
    'Stream Edge': Offset(offset=963, size=1, struct='B'),
    'Shadowrunner': Offset(offset=964, size=1, struct='B'),
    'Thirsty Edge': Offset(offset=965, size=1, struct='B'),
    'Blood Sacrifice': Offset(offset=966, size=1, struct='B'),
    'Upper Hand': Offset(offset=967, size=1, struct='B'),
    'Hundred Shells': Offset(offset=968, size=1, struct='B'),
    'Electric Surge': Offset(offset=969, size=1, struct='B'),
    'ARTS_HUGESHIELD_AUTO': Offset(offset=970, size=1, struct="B"),
    'Wild Down': Offset(offset=971, size=1, struct='B'),
    'Flame Cloak': Offset(offset=972, size=1, struct='B'),
    'Trash Talk': Offset(offset=973, size=1, struct='B'),
    'Iron Prison': Offset(offset=974, size=1, struct='B'),
    'Supershield': Offset(offset=975, size=1, struct='B'),
    'Wild Smash': Offset(offset=976, size=1, struct='B'),
    'Reality Rift': Offset(offset=977, size=1, struct='B'),
    'Bombardier': Offset(offset=978, size=1, struct='B'),
    'Shield Wall': Offset(offset=979, size=1, struct='B'),
    'ARTS_KNIFE_AUTO_Name': Offset(offset=980, size=1, struct="B"),
    'Screamer': Offset(offset=981, size=1, struct='B'),
    'Absorber Skin': Offset(offset=982, size=1, struct='B'),
    'Servant Sacrifice': Offset(offset=983, size=1, struct='B'),
    'Full Specs': Offset(offset=984, size=1, struct='B'),
    'Repair': Offset(offset=985, size=1, struct='B'),
    'Energy Source': Offset(offset=986, size=1, struct='B'),
    'Brainjack': Offset(offset=987, size=1, struct='B'),
    'Dispel': Offset(offset=988, size=1, struct='B'),
    'Black Butterfly': Offset(offset=989, size=1, struct='B'),
    'Recuperate': Offset(offset=990, size=1, struct='B'),
    'Chrome Armor': Offset(offset=991, size=1, struct='B'),
    'Slit Edge': Offset(offset=992, size=1, struct='B'),
    'ARTS_KNIFE_ARTS_13_N': Offset(offset=993, size=1, struct="B"),
    'ARTS_BEAMSABER_AUTO_': Offset(offset=994, size=1, struct="B"),
    'Geolibrium': Offset(offset=995, size=1, struct='B'),
    'Astrolibrium': Offset(offset=996, size=1, struct='B'),
    'Starfall Blade': Offset(offset=997, size=1, struct='B'),
    'Starfall Rondo': Offset(offset=998, size=1, struct='B'),
    'Astral Purge': Offset(offset=999, size=1, struct='B'),
    'Astral Horizon': Offset(offset=1000, size=1, struct='B'),
    'Galactic Cataclysm': Offset(offset=1001, size=1, struct='B'),
    'Astral Heal': Offset(offset=1002, size=1, struct='B'),
    'Novalibrium': Offset(offset=1003, size=1, struct='B'),
    'Starfall Blossom': Offset(offset=1004, size=1, struct='B'),
    'ARTS_ASSAULT_AUTO_Na': Offset(offset=1005, size=1, struct="B"),
    'Boost Barrel': Offset(offset=1006, size=1, struct='B'),
    'Sniper Barrel': Offset(offset=1007, size=1, struct='B'),
    'Missile Barrel': Offset(offset=1008, size=1, struct='B'),
    'Cannon Barrel': Offset(offset=1009, size=1, struct='B'),
    'Quick Cannon': Offset(offset=1010, size=1, struct='B'),
    'Grenade Blitz': Offset(offset=1011, size=1, struct='B'),
    'Overclock': Offset(offset=1012, size=1, struct='B'),
    'Afterburner': Offset(offset=1013, size=1, struct='B'),
    'Slayonet': Offset(offset=1014, size=1, struct='B'),
    'Ghost Factory': Offset(offset=1015, size=1, struct='B'),
    'Zero Zero': Offset(offset=1016, size=1, struct='B'),
    'Sky High': Offset(offset=1017, size=1, struct='B'),
    'Fire Carnival': Offset(offset=1018, size=1, struct='B'),
    'Bullet Twister': Offset(offset=1019, size=1, struct='B'),
    'Titan Recharge': Offset(offset=1020, size=1, struct='B'),
    'Master Gunner': Offset(offset=1021, size=1, struct='B'),
    'Clarity Ray': Offset(offset=1022, size=1, struct='B'),
    'Beam Bomber': Offset(offset=1023, size=1, struct='B'),
    'Dual Dynamo': Offset(offset=1024, size=1, struct='B'),
    'Gravity Lunge': Offset(offset=1025, size=1, struct='B'),
    'Tacit Censure': Offset(offset=1026, size=1, struct='B'),
    'Ultraslash': Offset(offset=1027, size=1, struct='B'),
    'Blossom Dance': Offset(offset=1028, size=1, struct='B'),
    'True Stream Edge': Offset(offset=1029, size=1, struct='B'),
    'Balance Breaker': Offset(offset=1030, size=1, struct='B'),
    'Vortex': Offset(offset=1031, size=1, struct='B'),
    'Maximum Voltage': Offset(offset=1032, size=1, struct='B'),
    'Shadowstrike': Offset(offset=1033, size=1, struct='B'),
    'Crisis Zone': Offset(offset=1034, size=1, struct='B'),
    'Seventh Edge': Offset(offset=1035, size=1, struct='B'),
    'Drum Roll': Offset(offset=1036, size=1, struct='B'),
    'Mindstorm': Offset(offset=1037, size=1, struct='B'),
    'Atomic Hit': Offset(offset=1038, size=1, struct='B'),
    'Flamehand': Offset(offset=1039, size=1, struct='B'),
    'Smooth Recovery': Offset(offset=1040, size=1, struct='B'),
    'Black Bane': Offset(offset=1041, size=1, struct='B'),
    'Secondary Speed': Offset(offset=1042, size=1, struct='B'),
    'Starlight Duster': Offset(offset=1043, size=1, struct='B'),
    'Essence Exchange': Offset(offset=1044, size=1, struct='B'),
    'Phenomenon': Offset(offset=1045, size=1, struct='B'),
}
skill_levels_offsets = {
    'Steel Flesh': Offset(offset=1145, size=1, struct='B'),
    'Unwavering Courage': Offset(offset=1146, size=1, struct='B'),
    'Flame Trigger': Offset(offset=1147, size=1, struct='B'),
    'Mighty Muscle': Offset(offset=1148, size=1, struct='B'),
    'Combat Presence': Offset(offset=1149, size=1, struct='B'),
    'Dismantler': Offset(offset=1150, size=1, struct='B'),
    'Agile Gunslinger': Offset(offset=1151, size=1, struct='B'),
    'Steady Hand': Offset(offset=1152, size=1, struct='B'),
    'Boosted Bullets': Offset(offset=1153, size=1, struct='B'),
    'Background Noise': Offset(offset=1154, size=1, struct='B'),
    'Combo Gunner': Offset(offset=1155, size=1, struct='B'),
    'Third Eye': Offset(offset=1156, size=1, struct='B'),
    'Master Edge': Offset(offset=1157, size=1, struct='B'),
    'Aura Burst': Offset(offset=1158, size=1, struct='B'),
    'Inner Search': Offset(offset=1159, size=1, struct='B'),
    'Beam Boost': Offset(offset=1160, size=1, struct='B'),
    'Beam Guard': Offset(offset=1161, size=1, struct='B'),
    'Buff Heal': Offset(offset=1162, size=1, struct='B'),
    'Healing Touch': Offset(offset=1163, size=1, struct='B'),
    'High Tension': Offset(offset=1164, size=1, struct='B'),
    'CQC Master': Offset(offset=1165, size=1, struct='B'),
    'Auto Melee Boost': Offset(offset=1166, size=1, struct='B'),
    'Iron Knuckle': Offset(offset=1167, size=1, struct='B'),
    'Healing Aura': Offset(offset=1168, size=1, struct='B'),
    'Weapon Guard': Offset(offset=1169, size=1, struct='B'),
    'Blazing Auto': Offset(offset=1170, size=1, struct='B'),
    'Theroid Slayer': Offset(offset=1171, size=1, struct='B'),
    'Yamato Spirit': Offset(offset=1172, size=1, struct='B'),
    'Thermal Shield': Offset(offset=1173, size=1, struct='B'),
    'Topple Topper': Offset(offset=1174, size=1, struct='B'),
    'Shield Screen': Offset(offset=1175, size=1, struct='B'),
    'Rising Renewal': Offset(offset=1176, size=1, struct='B'),
    'Long Topple': Offset(offset=1177, size=1, struct='B'),
    'Trauma Tension': Offset(offset=1178, size=1, struct='B'),
    'Dirty Fighter': Offset(offset=1179, size=1, struct='B'),
    'Stand Strong': Offset(offset=1180, size=1, struct='B'),
    'Deep Fang': Offset(offset=1181, size=1, struct='B'),
    'Mortal Enemy': Offset(offset=1182, size=1, struct='B'),
    'Trigger Happy': Offset(offset=1183, size=1, struct='B'),
    'Lifeline': Offset(offset=1184, size=1, struct='B'),
    'Mindscape': Offset(offset=1185, size=1, struct='B'),
    'Hellhound': Offset(offset=1186, size=1, struct='B'),
    'Killshot': Offset(offset=1187, size=1, struct='B'),
    'Electric Guard': Offset(offset=1188, size=1, struct='B'),
    'Electric Boost': Offset(offset=1189, size=1, struct='B'),
    "Knock 'n' Shock": Offset(offset=1190, size=1, struct='B'),
    'Fleet Feet': Offset(offset=1191, size=1, struct='B'),
    'Piscinoid Slayer': Offset(offset=1192, size=1, struct='B'),
    'Beauty Sleep': Offset(offset=1193, size=1, struct='B'),
    'Brain Wall': Offset(offset=1194, size=1, struct='B'),
    'Gentle Approach': Offset(offset=1195, size=1, struct='B'),
    "King's Decree": Offset(offset=1196, size=1, struct='B'),
    'Extra Armor': Offset(offset=1197, size=1, struct='B'),
    'Feather Touch': Offset(offset=1198, size=1, struct='B'),
    'Unpleasant Dream': Offset(offset=1199, size=1, struct='B'),
    'Core Crusher': Offset(offset=1200, size=1, struct='B'),
    'Ether Boost': Offset(offset=1201, size=1, struct='B'),
    'Mechanoid Slayer': Offset(offset=1202, size=1, struct='B'),
    "Knight's Soul": Offset(offset=1203, size=1, struct='B'),
    'Aura Assault': Offset(offset=1204, size=1, struct='B'),
    'Buff Extender': Offset(offset=1205, size=1, struct='B'),
    'Supreme Sword': Offset(offset=1206, size=1, struct='B'),
    'Conflagrant Edge': Offset(offset=1207, size=1, struct='B'),
    'Aggro Boost': Offset(offset=1208, size=1, struct='B'),
    'Fortified Flesh': Offset(offset=1209, size=1, struct='B'),
    'Grand Procession': Offset(offset=1210, size=1, struct='B'),
    'Machine Gunner': Offset(offset=1211, size=1, struct='B'),
    'Heatseeker': Offset(offset=1212, size=1, struct='B'),
    'Double Spike': Offset(offset=1213, size=1, struct='B'),
    'Double Reflect': Offset(offset=1214, size=1, struct='B'),
    'Night Vision': Offset(offset=1215, size=1, struct='B'),
    'Zero Lapse': Offset(offset=1216, size=1, struct='B'),
    'Red Zone': Offset(offset=1217, size=1, struct='B'),
    'Crisis Catalyst': Offset(offset=1218, size=1, struct='B'),
    'Blood Carnival': Offset(offset=1219, size=1, struct='B'),
    'Phantom Counter': Offset(offset=1220, size=1, struct='B'),
    'Long Shot': Offset(offset=1222, size=1, struct='B'),
    'Unstoppable': Offset(offset=1223, size=1, struct='B'),
    'Quick Reload': Offset(offset=1224, size=1, struct='B'),
    'Conductive Strike': Offset(offset=1225, size=1, struct='B'),
    'Electric Flesh': Offset(offset=1226, size=1, struct='B'),
    'TP Overdrive': Offset(offset=1227, size=1, struct='B'),
    'Ether Guard': Offset(offset=1228, size=1, struct='B'),
    'Gravity Boost': Offset(offset=1229, size=1, struct='B'),
    'Well-Weathered': Offset(offset=1230, size=1, struct='B'),
    'Appendage Erosion': Offset(offset=1231, size=1, struct='B'),
    'Resistant Flesh': Offset(offset=1232, size=1, struct='B'),
    'Tactical Analyst': Offset(offset=1233, size=1, struct='B'),
    "King's Boon": Offset(offset=1234, size=1, struct='B'),
    'Secondary Accelerator': Offset(offset=1235, size=1, struct='B'),
    'Gravity Guard': Offset(offset=1235, size=1, struct='B'),
    'Fast Forward': Offset(offset=1236, size=1, struct='B'),
    'Stellar Entry': Offset(offset=1237, size=1, struct='B'),
    'Synchrony': Offset(offset=1238, size=1, struct='B'),
}


# Display buffers above this value, according to
# https://gbatemp.net/threads/xcxgecko-xenoblade-chronicles-x-trainer-gui-using-pygecko.406442/post-5968675
buffers = 0x1C400000

# Only updates when menu is open (timer is onscreen)
timer = Address(0x1FB146E8, 12, ">III"),
